name: Installation Testing

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
  test-install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup testing environment
        run: |
          apt install libsndfile1 libsndfile1-dev
          pip install --upgrade pip
          pip install .
          python main.py --help
